model = "gpt-5.4"
service_tier = "fast"

[projects."/Users/fls/Workspace/System/dot-files"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp/oauth"

[mcp_servers.linear]
url = "https://mcp.linear.app/sse"

[mcp_servers.chrome-devtools]
command = "bunx"
args = ["chrome-devtools-mcp@latest"]
